language: node_js

node_js:
  - 7
  - 6

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g codecov

script:
  - npm run coverage

after_success:
  - npm run coveralls
